### ISSUE TITLE
question about the ReadMe.md and things about Apache-rat

### ISSUE THREAD

**Issue by jixuan1989** [WillemJiang/alc-site#14]
Hi,

I tried to compile the source code by following readme.md,

The question is, what is the difference between "Install hugo and run it" and "preview alc-site in local"?

Actually, the first one does not work because themes are lost.

Secondly, do we need to add Apache-rat on all files?

**Comment by WillemJiang** [comment]
You just need to follow the steps of "preview alc-site in local".   
As we don't have codes here, for the content of website, I think we may consider to use CC instead of ASL.

**Comment by jixuan1989** [comment]
OK.. let me delete the unused content...

> As we don't have codes here, for the content of website, I think we may consider to use CC instead of ASL.

It is fine. It seems that ASF does not emphasize whether to add apache header in website source files.

**Comment by WillemJiang** [comment]
FYI, there is an ASL in this rep now.
