### ISSUE TITLE
[翻译] 添加一篇介绍ASF如何召开正式成员会议的概述文档

### ISSUE THREAD

**Issue by sunjincheng121** [WillemJiang/alc-site#3]
ASF至少每13个月召开一次年度成员会议，选举新的董事会，并对新的成员候选人进行投票。在ALC-site增加对[1]的翻译文章，应该对国内用户很有帮助。
[1] https://www.apache.org/foundation/governance/meetings

**Comment by lijiangsheng1** [comment]
非常好的建议啊！

**Comment by sunjincheng121** [comment]
谢谢 建盛 肯定，我之前没有翻译过英文，坦白将我英语很差，第一次尝试，多多指教～ 
https://github.com/WillemJiang/alc-site/pull/4

**Comment by WillemJiang** [comment]
PR已合入。
