### ISSUE TITLE
[翻译] ASF组织架构

### ISSUE THREAD

**Issue by WillemJiang** [WillemJiang/alc-site#6]
最近ASF开了年度的成员大会， 涉及了新成员的选举，以及董事会成员的问题。 
我想应该有不少的人对ASF的治理，以及[组织架构](http://www.apache.org/foundation/governance/orgchart)比较感兴趣。
看看谁能帮忙翻译一下？

**Comment by sunjincheng121** [comment]
谢谢增加这个提议 Willem, 我试一下。

**Comment by WillemJiang** [comment]
@sunjincheng121 附上了图片的原文文件[链接](http://www.apache.org/foundation/governance/ApacheOrgChart.odg)

**Comment by sunjincheng121** [comment]
谢谢 @WillemJiang ，图片在原始页面有下载，我感觉将图片自己画一下，变成中文就更好了吧？
我创建了PR： [https://github.com/WillemJiang/alc-site/pull/8](https://github.com/WillemJiang/alc-site/pull/8)

**Comment by WillemJiang** [comment]
代码已合并。
